version: '3.4'
services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
  rails:
    build: ./
    restart: unless-stopped
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    environment:
      - RAILS_ENV=development
    ports:
      - '4000:3000'
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres: